##### GENERAL #####
set -g mouse on
set -g set-clipboard on
set -g default-terminal "screen-256color"
set -g history-limit 10000

set -g base-index 1
setw -g pane-base-index 1

##### RECARGAR CONFIG #####
bind r source-file ~/.tmux.conf \; display "Config recargada!"

##### SPLITS #####
bind | split-window -h
bind - split-window -v

##### COPY MODE (VI) - WAYLAND OPTIMIZED #####
set -g mode-keys vi
bind [ copy-mode

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "wl-copy"

##### PEGAR DESDE PORTAPAPELES DEL SISTEMA #####
bind ] run-shell "wl-paste -n | tmux load-buffer - && tmux paste-buffer"

##### VENTANAS #####
bind p previous-window
bind n next-window
