# ~/.config/starship.toml

format = """
[░▒▓](#3B4252)\
[  ](bg:#3B4252 fg:#E5E9F0)\
[](gen-bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[](fg:#4C566A bg:#88C0D0)\
$rust$nodejs$docker_context\
[](fg:#88C0D0 bg:#81A1C1)\
$time\
[ ](fg:#81A1C1)\
\n$character"""

[directory]
style = "bg:#434C5E fg:#E5E9F0"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = ""
style = "fg:#addb67" # Un verde oliva/lima muy suave (de Night Owl)
format = '[ $symbol $branch ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#7fdbca" # Un cian relajado para la fecha
format = 'at [$time]($style) '

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
