# ~/.config/starship.toml

format = """
[░▒▓](#3B4252)\
[  ](bg:#3B4252 fg:#E5E9F0)\
[](gen-bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[](fg:#4C566A bg:#88C0D0)\
$rust$nodejs$docker_context\
[](fg:#88C0D0 bg:#81A1C1)\
$time\
[ ](fg:#81A1C1)\
\n$character"""

[directory]
style = "bg:#434C5E fg:#E5E9F0"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = ""
style = "bg:#4C566A fg:#E5E9F0"
format = '[[ $symbol $branch ](bg:#4C566A fg:#E5E9F0)]($style)'

[time]
disabled = false
time_format = "%R" # Hora militar
style = "bg:#81A1C1 fg:#2E3440"
format = '[[  $time ](bg:#81A1C1 fg:#2E3440)]($style)'

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
