# ~/.config/starship.toml

format = """
[░▒▓](#011627)\
[ 󰣇 ](bg:#011627 fg:#82aaff)\
[](fg:#011627 bg:#1e3140)\
$directory\
[](fg:#1e3140 bg:#2d4252)\
$git_branch\
$git_status\
[](fg:#2d4252 bg:#82aaff)\
$rust$nodejs$docker_context\
[](fg:#82aaff bg:#011627)\
$time\
[ ](fg:#011627)\
\n$character"""

[directory]
style = "bg:#1e3140 fg:#addb67"
format = "[ 󰉋 $path ]($style)"
truncation_length = 3

[git_branch]
symbol = ""
style = "bg:#2d4252 fg:#82aaff"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#2d4252 fg:#ef5350"
format = '([$all_status$ahead_behind]($style))'

[time]
disabled = false
time_format = "%R"
style = "bg:#011627 fg:#ecc48d"
format = '[ 󱑒 $time ]($style)'

[docker_context]
symbol = " "
style = "bg:#82aaff fg:#011627"
format = '[ $symbol ]($style)'

[character]
success_symbol = "[⚡](bold #addb67)"
error_symbol = "[✖](bold #ef5350)"
